export const MobileMaxWidth = "500px"
export const TabletMinWidth = "501px"
export const TabletMaxWidth = "900px"
export const DesktopMinWidth = "901px"
export const HeaderHeightMobile = "45px"
export const HeaderHeightDesktop = "45px"